import { BSSPoint } from "@/types/bssPoints";

export const bssPoints: BSSPoint[] = [
  {
    id: "1",
    name: "Lencar BSS Miriswaththa",
    region: "Western",
    district: "Gampaha",
    address: "84/C, Miriswatta, Muduugoda, Gampaha",
    lat: 7.074552,
    lng: 80.01495,
    hours: "Open 24 hours",
    mapsQuery: "84/C, Miriswatta, Muduugoda, Gampaha",
  },
  {
    id: "2",
    name: "Lencar BSS Seeduwa",
    region: "Western",
    district: "Gampaha",
    address: "73, Liyanagemulla, Seeduwa",
    lat: 7.1329664,
    lng: 79.8883593,
    hours: "Open 24 hours",
    mapsQuery: "73, Liyanagemulla, Seeduwa",
  },
  {
    id: "3",
    name: "Lencar BSS Katunayake",
    region: "Western",
    district: "Gampaha",
    address: "128, 18th Mile Post, Katunayake",
    lat: 7.1552381,
    lng: 79.8718722,
    hours: "Open 24 hours",
    mapsQuery: "128, 18th Mile Post, Katunayake",
  },
  {
    id: "4",
    name: "Lencar BSS Udugampola",
    region: "Western",
    district: "Gampaha",
    address: "140 Dobawala, Udugampola",
    lat: 7.120514,
    lng: 79.98395,
    hours: "Open 24 hours",
    mapsQuery: "140 Dobawala, Udugampola",
  },
  {
    id: "5",
    name: "Lencar BSS Kadawatha",
    region: "Western",
    district: "Gampaha",
    address: "Subodha Mawatha, Kadawatha",
    lat: 7.006708,
    lng: 79.9582,
    hours: "Open 24 hours",
    mapsQuery: "Subodha Mawatha, Kadawatha",
  },
  {
    id: "6",
    name: "Lencar BSS Kiribathgoda",
    region: "Western",
    district: "Gampaha",
    address: "89/16, Jinadasa Nandasena Mawatha, Kiribathgoda",
    lat: 6.9787082,
    lng: 79.9301695,
    hours: "Open 24 hours",
    mapsQuery:
      "89/16, Jinadasa Nandasena Mawatha, Kiribathgoda",
  },
  {
    id: "7",
    name: "Lencar BSS Kochchikade",
    region: "Western",
    district: "Puttalam",
    address:
      "Thopputhota Filling Station, Chilaw-Colombo Main Rd, 61110",
    lat: 7.27417,
    lng: 79.86241,
    hours: "Open 24 hours",
    mapsQuery:
      "Thopputhota Filling Station, Chilaw-Colombo Main Rd, 61110",
  },
  {
    id: "8",
    name: "Lencar BSS Paliyagoda",
    region: "Western",
    district: "Gampaha",
    address: "3 Negombo Rd, Wattala 11300",
    lat: 6.961071,
    lng: 79.88095,
    hours: "Open 24 hours",
    mapsQuery: "3 Negombo Rd, Wattala 11300",
  },
  {
    id: "9",
    name: "Lencar BSS Thalawathugoda",
    region: "Western",
    district: "Colombo",
    address: "263/1, Hokandara Rd, Ruhunupura",
    lat: 6.877135,
    lng: 79.938515,
    hours: "Open 24 hours",
    mapsQuery: "263/1, Hokandara Rd, Ruhunupura",
  },
  {
    id: "10",
    name: "Lencar BSS Rawatawatta",
    region: "Western",
    district: "Colombo",
    address: "Rawatawatta Junction, Galle Road, Moratuwa",
    lat: 6.787884,
    lng: 79.8853,
    hours: "Open 24 hours",
    mapsQuery: "Rawatawatta Junction, Galle Road, Moratuwa",
  },
  {
    id: "11",
    name: "Lencar BSS Soysapura",
    region: "Western",
    district: "Colombo",
    address: "164, Soysapura, Moratuwa",
    lat: 6.91519,
    lng: 79.88125,
    hours: "Open 24 hours",
    mapsQuery: "164, Soysapura, Moratuwa",
  },
  {
    id: "12",
    name: "Lencar BSS Kolonnawa",
    region: "Western",
    district: "Colombo",
    address: "595, Kolonnawa Road, Wellampitiya",
    lat: 6.936831,
    lng: 79.89584,
    hours: "Open 24 hours",
    mapsQuery: "595, Kolonnawa Road, Wellampitiya",
  },
  {
    id: "13",
    name: "Lencar BSS Borella",
    region: "Western",
    district: "Colombo",
    address:
      "Thilakarathnaramaya Temple, Ward Place, Colombo 08",
    lat: 6.8664,
    lng: 80.0166,
    hours: "Open 24 hours",
    mapsQuery:
      "Thilakarathnaramaya Temple, Ward Place, Colombo 08",
  },
  {
    id: "14",
    name: "Lencar BSS Padukka",
    region: "Western",
    district: "Colombo",
    address:
      "77/7/1, Polgahahota, Wewelktiya Bope, Padukka",
    lat: 6.8418333,
    lng: 80.1029167,
    hours: "Open 24 hours",
    mapsQuery:
      "77/7/1, Polgahahota, Wewelktiya Bope, Padukka",
  },
  {
    id: "15",
    name: "Lencar BSS Beruwala",
    region: "Western",
    district: "Kalutara",
    address: "Galle Rd, Beruwala",
    lat: 6.4742578,
    lng: 79.9837669,
    hours: "Open 24 hours",
    mapsQuery: "Galle Rd, Beruwala",
  },
  {
    id: "16",
    name: "Lencar BSS Bandaragama",
    region: "Western",
    district: "Kalutara",
    address: "17A, Horana Rd, Bandaragama",
    lat: 6.71478474823078,
    lng: 79.9891399402368,
    hours: "Open 24 hours",
    mapsQuery: "17A, Horana Rd, Bandaragama",
  },
  {
    id: "17",
    name: "Lencar BSS Maggona",
    region: "Western",
    district: "Kalutara",
    address: "150/A, Galle Road, Diyalagoda, Maggona",
    lat: 6.507246,
    lng: 79.981156,
    hours: "Open 24 hours",
    mapsQuery: "150/A, Galle Road, Diyalagoda, Maggona",
  },
  {
    id: "18",
    name: "Lencar BSS Panadura",
    region: "Western",
    district: "Kalutara",
    address:
      "43A, Janapriya Mawatha, Awariyawatta, Alubomulla, Panadura",
    lat: 6.7100089,
    lng: 79.9149443,
    hours: "Open 24 hours",
    mapsQuery:
      "43A, Janapriya Mawatha, Awariyawatta, Alubomulla, Panadura",
  },
  {
    id: "19",
    name: "Lencar BSS Agalawaththa",
    region: "Western",
    district: "Kalutara",
    address: "226/01, Yatiyana, Agalawatta",
    lat: 6.5349563,
    lng: 80.1499513,
    hours: "Open 24 hours",
    mapsQuery: "226/01, Yatiyana, Agalawatta",
  },
  {
    id: "20",
    name: "Lencar BSS Kalutara",
    region: "Western",
    district: "Kalutara",
    address:
      "3B, St. Philipneres Church Road, Katukurunda",
    lat: 6.561314,
    lng: 79.967797,
    hours: "Open 24 hours",
    mapsQuery:
      "3B, St. Philipneres Church Road, Katukurunda",
  },
  {
    id: "21",
    name: "Lencar BSS Dharga Town",
    region: "Western",
    district: "Kalutara",
    address: "87/02, Main Street, Darga Town",
    lat: 6.4412313,
    lng: 80.0111424,
    hours: "Open 24 hours",
    mapsQuery: "87/02, Main Street, Darga Town",
  },
  {
    id: "22",
    name: "Lencar BSS Kurunegala",
    region: "North Western",
    district: "Kurunegala",
    address:
      "44, Narammala-Madampe Road, Kurunegala",
    lat: 7.4803378,
    lng: 80.3505175,
    hours: "Open 24 hours",
    mapsQuery:
      "44, Narammala-Madampe Road, Kurunegala",
  },
  {
    id: "23",
    name: "Lencar BSS Kuliyapitiya",
    region: "North Western",
    district: "Kurunegala",
    address:
      "190, Uthurawala, Welipannagahamulla, Kuliyapitiya",
    lat: 7.4699121,
    lng: 80.0265886,
    hours: "Open 24 hours",
    mapsQuery:
      "190, Uthurawala, Welipannagahamulla, Kuliyapitiya",
  },
];